name: Continuous Integration
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.1
        with:
          linter: pylint


  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: user/app:latest
  #discord:
   # runs-on: ubuntu-latest
    #steps:

    #- uses: actions/checkout@v4
    #- name: Run Discord Webhook
      #uses: johnnyhuy/actions-discord-git-webhook@main
      #with:
        #webhook_url: ${{ secrets.DISCORD_WEBHOOK }}

discord:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "hugoalh/send-discord-webhook-ghaction@v7.0.0"
        with:
          key: "${{secrets.DISCORD-WEBHOOK}}"
          content: "Hello, world!"